import type {Metadata} from "next";
import { Inter, Doto } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@/assets/scss/main.scss";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const doto = Doto({
  variable: "--font-doto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${doto.variable}`}>
        {children}
      </body>
    </html>
  );
}
